### ISSUE TITLE
"type" for exception in "Catch" grammar rule must be a "VariableDeclaration" and not a "Variable" (reference)

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok-js#10]
See here

```
catch = _ 'catch' __ variable:variable _ type:(':' _ qualifiedName)? _ handler:blockOrSentence { return Catch(variable,type?type[2]:undefined)(...handler) }
```

I think that there is a mistake as the catch doesn't reference a variable but declare one, just like a closure parameter or method parameters.. 

Currently the linker fails with this

```
try {

}
catch e {
}
```

With `Cannot resolve reference to 'e' at ???`
Because as it is a "Variable" it assumes is a reference and not a declaration.

I think that this should be changed in the grammar.
@nscarcella am I right ?

**Comment by nscarcella** [comment]
I'm not sure... I see that semantically it's clearly not a variable, but syntactically is quite far from a variable declaration. How about a parameter? @javierfernandez

**Comment by javierfernandes** [comment]
Yes sorry. A var dec has the modifier like const var etc. param sounds
better

**Comment by nscarcella** [comment]
Fixed on latest head
