### ISSUE TITLE
Wollok must not support "instanceof"

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok-js#12]
Hey @nscarcella .. I'm not sure if it came from wollok xtext grammar, if so then that is also wrong,
but I think that wollok doesn't currently support "instance of" operator, and it will never do so :)

So I think that we can remove this parsing rule

```
export const InstanceOf = (left, right) => Node(InstanceOf, location)({ left, right })
```

**Comment by nscarcella** [comment]
@javierfernandes hehe, it came from current Wollok grammar.

I tried it on Wollok Freire and, as you said, it is not supported. Will remove this from this version soon.
